-- Script to insert initial categories for the Online Store
-- These will only be visible in the online storefront and online admin panel.

INSERT INTO categories (name, color, icon, store_type) VALUES
('7C Baking Ingredients', '#FFD1DC', '🧁', 'online'),
('Aluminum Moulds', '#FFB347', '🥧', 'online'),
('Appliances Mixers', '#B19CD9', '🥣', 'online'),
('Arife Wow Sale', '#FF6961', '🏷️', 'online'),
('Bake & Serve', '#77DD77', '🍮', 'online'),
('Baking Ingredients', '#AEC6CF', '🧂', 'online'),
('Baking Tools & Accessories', '#FDFD96', '🛠️', 'online'),
('Piping Nozzles', '#CFCFC4', '🍦', 'online'),
('Brands', '#F49AC2', '⭐', 'online'),
('Cake And Cupcake Stand', '#CB99C9', '🎂', 'online'),
('Cake Base', '#FFD1DC', '🍰', 'online'),
('Cake Dummies', '#FFB347', '🎂', 'online'),
('Cake Toppers', '#B19CD9', '✨', 'online'),
('Chocolate And Cupcake Boxes', '#FF6961', '🎁', 'online'),
('Chocolate Wrappers', '#77DD77', '🍫', 'online'),
('Cutters', '#AEC6CF', '✂️', 'online'),
('Diwali Mould', '#FDFD96', '🪔', 'online'),
('Diy Stamps Fondant Embosser', '#CFCFC4', '🎨', 'online'),
('Feather', '#F49AC2', '🪶', 'online'),
('Festival Themes', '#CB99C9', '🎉', 'online'),
('Knives And Spatula', '#FFD1DC', '🔪', 'online'),
('Kulfi Moulds', '#FFB347', '🍧', 'online'),
('Leafs And Flakes', '#B19CD9', '🍂', 'online'),
('Non Edible Dust', '#FF6961', '✨', 'online'),
('Non Stick Moulds', '#77DD77', '🍳', 'online'),
('Nylon Spoon', '#AEC6CF', '🥄', 'online'),
('Party Supplies', '#FDFD96', '🎈', 'online'),
('Polycarbonate Moulds', '#CFCFC4', '🧊', 'online'),
('Pvc Mould', '#F49AC2', '🥡', 'online'),
('Resin Arts', '#CB99C9', '🖌️', 'online'),
('Scraper', '#FFD1DC', '🧰', 'online'),
('Selfie Mirror', '#FFB347', '🪞', 'online'),
('Silicon Moulds', '#B19CD9', '🥟', 'online'),
('Sprinklers And Candies', '#FF6961', '🍬', 'online'),
('Stencils', '#77DD77', '🎨', 'online'),
('Sticker', '#AEC6CF', '🏷️', 'online'),
('Ultimakes', '#FDFD96', '🏆', 'online');
